"""add Group Request

Revision ID: 03105f6044a0
Revises: 2028be1a61af
Create Date: 2021-01-03 10:30:12.695148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03105f6044a0'
down_revision = '2028be1a61af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user', sa.Integer(), nullable=True),
    sa.Column('receiver_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_group'], ['user_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_request')
    # ### end Alembic commands ###
