"""empty message

Revision ID: 2028be1a61af
Revises: 1e7cfc7bd136
Create Date: 2021-01-01 11:33:08.979292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2028be1a61af'
down_revision = '1e7cfc7bd136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_engagement', sa.Column('day', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_engagement', 'day')
    # ### end Alembic commands ###
