"""empty message

Revision ID: 41c26af3cd58
Revises: f4019c9c841b
Create Date: 2020-11-18 19:45:05.997001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41c26af3cd58'
down_revision = 'f4019c9c841b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('group_ibfk_1', 'group', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('group_ibfk_1', 'group', 'user', ['group_admin'], ['id'])
    # ### end Alembic commands ###
