"""edit tables

Revision ID: 527aaec70ca1
Revises: 6b68527f9ae8
Create Date: 2021-01-10 19:52:09.587903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '527aaec70ca1'
down_revision = '6b68527f9ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_engagement', sa.Column('date', sa.String(length=100), nullable=True))
    op.drop_column('group_engagement', 'day')
    op.drop_column('group_engagement', 'am_pm')
    op.drop_column('group_engagement', 'month')
    op.drop_column('group_engagement', 'weekday')
    op.add_column('user_engagement', sa.Column('date', sa.String(length=100), nullable=True))
    op.drop_column('user_engagement', 'day')
    op.drop_column('user_engagement', 'am_pm')
    op.drop_column('user_engagement', 'month')
    op.drop_column('user_engagement', 'weekday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_engagement', sa.Column('weekday', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user_engagement', sa.Column('month', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('user_engagement', sa.Column('am_pm', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('user_engagement', sa.Column('day', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('user_engagement', 'date')
    op.add_column('group_engagement', sa.Column('weekday', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('group_engagement', sa.Column('month', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('group_engagement', sa.Column('am_pm', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('group_engagement', sa.Column('day', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('group_engagement', 'date')
    # ### end Alembic commands ###
