"""empty message

Revision ID: 6b68527f9ae8
Revises: a1b0baeb1ab3
Create Date: 2021-01-03 14:18:16.114119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b68527f9ae8'
down_revision = 'a1b0baeb1ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_user', sa.Integer(), nullable=True),
    sa.Column('receiver_group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_group'], ['user_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_request')
    # ### end Alembic commands ###
