"""empty message

Revision ID: 72ab9896cd61
Revises: c188c2ac1c6b
Create Date: 2020-11-19 10:14:32.044298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72ab9896cd61'
down_revision = 'c188c2ac1c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friended_id', sa.Integer(), nullable=True))
    op.add_column('friends', sa.Column('friender_id', sa.Integer(), nullable=True))
    op.drop_constraint('friends_ibfk_2', 'friends', type_='foreignkey')
    op.drop_constraint('friends_ibfk_1', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'user', ['friender_id'], ['id'])
    op.create_foreign_key(None, 'friends', 'user', ['friended_id'], ['id'])
    op.drop_column('friends', 'friended')
    op.drop_column('friends', 'friender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('friends', sa.Column('friended', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_ibfk_1', 'friends', 'user', ['friended'], ['id'])
    op.create_foreign_key('friends_ibfk_2', 'friends', 'user', ['friender'], ['id'])
    op.drop_column('friends', 'friender_id')
    op.drop_column('friends', 'friended_id')
    # ### end Alembic commands ###
