"""empty message

Revision ID: 762217bc1b0d
Revises: 7292606867a7
Create Date: 2020-11-18 19:04:21.950106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762217bc1b0d'
down_revision = '7292606867a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_engagement', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_engagement', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_engagement', type_='foreignkey')
    op.drop_column('user_engagement', 'user_id')
    # ### end Alembic commands ###
