"""empty message

Revision ID: 78777d9afa84
Revises: cdedfb1dc20d
Create Date: 2020-11-25 16:57:40.022644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78777d9afa84'
down_revision = 'cdedfb1dc20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_engagement', sa.Column('day', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_engagement', 'day')
    # ### end Alembic commands ###
