"""empty message

Revision ID: 7a5f563ea849
Revises: ed2bf7b9c631
Create Date: 2020-12-30 20:11:25.519794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a5f563ea849'
down_revision = 'ed2bf7b9c631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_request', sa.Column('receiver_id', sa.Integer(), nullable=True))
    op.add_column('friend_request', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.drop_constraint('friend_request_ibfk_1', 'friend_request', type_='foreignkey')
    op.create_foreign_key(None, 'friend_request', 'user', ['receiver_id'], ['id'])
    op.drop_column('friend_request', 'receiver')
    op.drop_column('friend_request', 'sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_request', sa.Column('sender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('friend_request', sa.Column('receiver', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friend_request', type_='foreignkey')
    op.create_foreign_key('friend_request_ibfk_1', 'friend_request', 'user', ['receiver'], ['id'])
    op.drop_column('friend_request', 'sender_id')
    op.drop_column('friend_request', 'receiver_id')
    # ### end Alembic commands ###
