"""empty message

Revision ID: 971b56f267ed
Revises: f18a697a0372
Create Date: 2020-11-20 09:38:09.946779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '971b56f267ed'
down_revision = 'f18a697a0372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_group', 'group_member_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('group_member_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
