"""empty message

Revision ID: 9a417b79de83
Revises: 78777d9afa84
Create Date: 2020-11-25 17:05:00.999642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a417b79de83'
down_revision = '78777d9afa84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_engagement', sa.Column('is_published_groupies', sa.Boolean(), nullable=True))
    op.add_column('user_engagement', sa.Column('is_published_mates', sa.Boolean(), nullable=True))
    op.drop_column('user_engagement', 'is_published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_engagement', sa.Column('is_published', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('user_engagement', 'is_published_mates')
    op.drop_column('user_engagement', 'is_published_groupies')
    # ### end Alembic commands ###
