"""name change

Revision ID: c188c2ac1c6b
Revises: d358395ed581
Create Date: 2020-11-19 10:12:27.921237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c188c2ac1c6b'
down_revision = 'd358395ed581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friended', sa.Integer(), nullable=True))
    op.add_column('friends', sa.Column('friender', sa.Integer(), nullable=True))
    op.drop_constraint('friends_ibfk_2', 'friends', type_='foreignkey')
    op.drop_constraint('friends_ibfk_1', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'user', ['friended'], ['id'])
    op.create_foreign_key(None, 'friends', 'user', ['friender'], ['id'])
    op.drop_column('friends', 'friend1_id')
    op.drop_column('friends', 'friend2_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('friend2_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('friends', sa.Column('friend1_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_ibfk_1', 'friends', 'user', ['friend1_id'], ['id'])
    op.create_foreign_key('friends_ibfk_2', 'friends', 'user', ['friend2_id'], ['id'])
    op.drop_column('friends', 'friender')
    op.drop_column('friends', 'friended')
    # ### end Alembic commands ###
