"""empty message

Revision ID: ed60bf4996df
Revises: 41c26af3cd58
Create Date: 2020-11-18 20:03:09.497973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed60bf4996df'
down_revision = '41c26af3cd58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'group', 'user', ['group_admin'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    # ### end Alembic commands ###
