"""readded fk's

Revision ID: f4019c9c841b
Revises: 8468c476f3ae
Create Date: 2020-11-18 19:32:10.608222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4019c9c841b'
down_revision = '8468c476f3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('group_admin', sa.Integer(), nullable=True),
    sa.Column('group_desc', sa.String(length=128), nullable=True),
    sa.Column('group_member_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_group_name'), 'group', ['group_name'], unique=True)
    op.create_foreign_key(None, 'user_friend_pairs', 'user', ['second_user'], ['id'])
    op.create_foreign_key(None, 'user_friend_pairs', 'user', ['first_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_friend_pairs', type_='foreignkey')
    op.drop_constraint(None, 'user_friend_pairs', type_='foreignkey')
    op.drop_index(op.f('ix_group_group_name'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
