"""empty message

Revision ID: ff6d51c2def3
Revises: ed60bf4996df
Create Date: 2020-11-18 20:04:46.964318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff6d51c2def3'
down_revision = 'ed60bf4996df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=50), nullable=True),
    sa.Column('group_admin', sa.Integer(), nullable=True),
    sa.Column('group_desc', sa.String(length=128), nullable=True),
    sa.Column('group_member_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_admin'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_group_group_name'), 'user_group', ['group_name'], unique=True)
    op.drop_index('ix_group_group_name', table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('group_admin', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('group_desc', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('group_member_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_admin'], ['user.id'], name='group_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_group_group_name', 'group', ['group_name'], unique=True)
    op.drop_index(op.f('ix_user_group_group_name'), table_name='user_group')
    op.drop_table('user_group')
    # ### end Alembic commands ###
